Elasticache core module
moengage/tf-core pull request #18
Opened 2021-05-24 07:01 UTC by ummiyah-moe

2021-05-26 00:32 UTC, sudip-moengage requested changes
Few other changes:
- Move this module to `elasticache/redis` directory
- Please add an example in terragrunt repo: https://github.com/moengage/terragrunt/tree/master/staging/ap-south-1/default/sre/examples

2021-05-26 00:32 UTC, sudip-moengage commented on elasticache/locals.tf
> +  _subservice_name     = coalesce(var.subservice_name, var.service_name)
subservice_name is not optional, so you can remove this line and just use `var.subservice_name` everywhere.

2021-05-26 00:32 UTC, sudip-moengage commented on elasticache/locals.tf
> +    SubService  = lower(local._subservice_name)
var.subservice_name

2021-05-26 00:32 UTC, sudip-moengage commented on elasticache/variables.tf
> +  default     = []
It should be mandatory I guess?

2021-05-26 00:32 UTC, sudip-moengage commented on elasticache/variables.tf
> +  default     = false
default true

2021-05-26 00:32 UTC, sudip-moengage commented on elasticache/variables.tf
> +  default     = ""
enable this, if needed create kms key. Security team wants us to encrypt everything we have at rest.

2021-05-26 00:32 UTC, sudip-moengage commented on elasticache/variables.tf
> +  description = "Created by"
let's deprecate this field. make it default=""

2021-05-27 17:35 UTC, ummiyah-moe commented on elasticache/locals.tf
> +  _subservice_name     = coalesce(var.subservice_name, var.service_name)
Updated.

2021-05-27 17:36 UTC, ummiyah-moe commented on elasticache/variables.tf
> +  description = "Created by"
removed this field from module.

2021-05-27 17:36 UTC, ummiyah-moe commented on elasticache/variables.tf
> +  default     = ""
used aws default kms key.

2021-05-27 17:37 UTC, ummiyah-moe commented
@sudip-moengage  1. Fixed dir and comments
2. https://github.com/moengage/terragrunt/pull/103 will update source of terragrunt after this PR is merged.

2021-05-29 10:11 UTC, merged