Add: rds-mysql core module
moengage/tf-core pull request #19
Opened 2021-05-25 07:56 UTC by ummiyah-moe

2021-05-26 00:49 UTC, sudip-moengage requested changes
- Move this module to `rds/mysql` directory
- Add an example in terragrunt repo.

2021-05-26 00:49 UTC, sudip-moengage commented on rds-mysql/locals.tf
> +  _subservice_name       = coalesce(var.subservice_name, var.service_name)
subservice_name is mandatory variable, we can remove this coalesce.

2021-05-26 00:49 UTC, sudip-moengage commented on rds-mysql/locals.tf
> +  _resource_identifier   = "${var.business_name}-${var.service_name}-${local._subservice_name}"
var.subservice_name

2021-05-26 00:49 UTC, sudip-moengage commented on rds-mysql/main.tf
> +
extra line.

2021-05-26 00:49 UTC, sudip-moengage commented on rds-mysql/main.tf
> +# https://www.terraform.io/docs/providers/aws/r/db_option_group.html
run `terraform fmt`

2021-05-26 00:49 UTC, sudip-moengage commented on rds-mysql/variables.tf
> +  type        = string
let's deprecate this variable.

2021-05-26 00:49 UTC, sudip-moengage commented on rds-mysql/variables.tf
> +  default     = true
default = `false`

2021-05-26 00:49 UTC, sudip-moengage commented on rds-mysql/variables.tf
> +  default     = true
default = false

2021-05-26 00:49 UTC, sudip-moengage commented on rds-mysql/variables.tf
> +  default     = false
true

2021-05-26 00:49 UTC, sudip-moengage commented on rds-mysql/variables.tf
> +  default     = ""
if needed autocreate kms key and make it mandatory or automated

2021-05-26 00:49 UTC, sudip-moengage commented on rds-mysql/variables.tf
> +  default     = ""
shouldn't here be a default redis version?

2021-05-26 00:49 UTC, sudip-moengage commented on rds-mysql/variables.tf
> +  default     = []
shouldn't this be mandatory?

2021-05-27 16:08 UTC, ummiyah-moe commented on rds-mysql/locals.tf
> +  _subservice_name       = coalesce(var.subservice_name, var.service_name)
Updated.

2021-05-27 16:09 UTC, ummiyah-moe commented on rds-mysql/variables.tf
> +  default     = []
updated.

2021-05-27 16:09 UTC, ummiyah-moe commented on rds-mysql/main.tf
> +# https://www.terraform.io/docs/providers/aws/r/db_option_group.html
updated.

2021-05-27 16:10 UTC, ummiyah-moe commented
@sudip-moengage 1. Fixed dir structure and comments
2. https://github.com/moengage/terragrunt/pull/102

2021-05-29 10:28 UTC, sudip-moengage requested changes
This PR contains change from cloudwatch modules as well, which is merged to master and reverted back. Please rebase your branch with master.

2021-05-29 10:28 UTC, sudip-moengage commented on rds/mysql/variables.tf
> +  default     = true
default = false

2021-05-29 10:28 UTC, sudip-moengage commented on rds/mysql/variables.tf
> +variable "monitoring_interval" {
Does this module support enhance monitoring? If it's not we should implement it.

2021-05-29 10:28 UTC, sudip-moengage commented on rds/mysql/variables.tf
> +variable "kms_key_id" {
Is this tested? Is AWS creates an KMS key automatically to encrypt the storage?

2021-05-29 10:28 UTC, sudip-moengage commented on rds/mysql/variables.tf
> +
extra line

2021-05-29 10:28 UTC, sudip-moengage commented on rds/.terraform.lock.hcl
> +# This file is maintained automatically by "terraform init".
Let's not commit this file for now.

2021-05-29 10:28 UTC, sudip-moengage commented on cloudwatch/sqs_alarms/variables.tf
> +}
add line break

2021-05-29 10:28 UTC, sudip-moengage commented on cloudwatch/sqs_alarms/sqs_alarms.tf
> +resource "aws_cloudwatch_metric_alarm" "reports-sqs-msgs-alarm" {
why reports? Why this PR contains change from sqs_alarms? If needed create a separate PR to do the changes.

2021-05-31 06:19 UTC, ummiyah-moe commented on rds/mysql/variables.tf
> +variable "kms_key_id" {
Yes. For every services, aws provides default kms, since most of our services uses default kms so i have used same here.

2021-05-31 06:26 UTC, ummiyah-moe commented on rds/mysql/variables.tf
> +variable "monitoring_interval" {
Yes. you can set the monitoring_interval variable. - The interval, in seconds, between points when Enhanced Monitoring metrics are collected for the DB instance. To disable collecting Enhanced Monitoring metrics, specify 0. The default is 0.

2021-05-31 06:32 UTC, ummiyah-moe commented on cloudwatch/sqs_alarms/sqs_alarms.tf
> +resource "aws_cloudwatch_metric_alarm" "reports-sqs-msgs-alarm" {
Updated.

2021-06-10 12:12 UTC, sudip-moengage commented
@ummiyah-moe Let's add postgres as well.

2021-07-09 07:15 UTC, merged