Cloudwatch alarms
moengage/tf-core pull request #22
Opened 2021-05-31 12:46 UTC by rajkumar-moengage

2021-05-31 13:20 UTC, sudip-moengage requested changes

2021-05-31 13:20 UTC, sudip-moengage commented on cloudwatch/sqs_alarms/sqs_alarms.tf
> +resource "aws_cloudwatch_metric_alarm" "reports-sqs-msgs-alarm" {
name should be generic. please don't include business name here.

2021-05-31 13:20 UTC, sudip-moengage commented on load_balancers/application/alb.tf
> +  count                   = var.alb_default_alarm_creation ? 1 : 0
change variable name to `create_default_alrms`

2021-05-31 13:20 UTC, sudip-moengage commented on load_balancers/application/variables.tf
> +  type        = list(any)
Optional variable

2021-05-31 13:20 UTC, sudip-moengage commented on cloudwatch/sqs_alarms/variables.tf
> +
Unnecessary extra line

2021-05-31 13:20 UTC, sudip-moengage commented on cloudwatch/sqs_alarms/variables.tf
> +variable "dimensions_queuename" {
No new line between two variable

2021-05-31 13:20 UTC, sudip-moengage commented on cloudwatch/sqs_alarms/variables.tf
> +variable "sqs_msgs_threshold" {
No new line between two variable

2021-05-31 13:20 UTC, sudip-moengage commented on cloudwatch/sqs_alarms/variables.tf
> +
Unnecessary extra line

2021-05-31 13:20 UTC, sudip-moengage commented on cloudwatch/sqs_alarms/variables.tf
> +variable "evaluation_periods" {
No new line between two variable

2021-05-31 13:20 UTC, sudip-moengage commented on cloudwatch/sqs_alarms/sqs_alarms.tf
> +resource "aws_cloudwatch_metric_alarm" "reports-sqs-msgs-alarm" {
Move this folder to cloudwatch/sqs

2021-05-31 13:20 UTC, sudip-moengage commented on cloudwatch/alb_alarms/README.md
> +## Requirements
Move this folder to ckoudwatch/application_lb

2021-05-31 13:20 UTC, sudip-moengage commented on cloudwatch/alb_alarms/variables.tf
> +}
space between variables should be consistent

2021-05-31 13:20 UTC, sudip-moengage commented on cloudwatch/alb_tg_alarms/alb_tg_alarms.tf
> +resource "aws_cloudwatch_metric_alarm" "tg-5xx-alarm" {
Move this folder to cloudwatch/target_group

2021-05-31 13:20 UTC, sudip-moengage commented on cloudwatch/alb_tg_alarms/variables.tf
> +variable "tg_name" {
Variable space should be consistent, we follow an extra empty new line between variables

2021-05-31 13:20 UTC, sudip-moengage commented on cloudwatch/sqs_alarms/README.md
> +## Requirements
Move this folder to cloudwatch/sqs

2021-05-31 13:30 UTC, rajkumar-moengage commented on cloudwatch/sqs_alarms/sqs_alarms.tf
> +resource "aws_cloudwatch_metric_alarm" "reports-sqs-msgs-alarm" {
why inside "sqs" ?. already its inside "sqs_alarms" right

2021-05-31 13:43 UTC, sudip-moengage requested changes

2021-05-31 13:43 UTC, sudip-moengage commented on load_balancers/application/alb.tf
> +  source                  = "git@github.com:moengage/tf-core.git//cloudwatch/alb_alarms?ref=master"
This need to point to correct path

2021-05-31 13:43 UTC, sudip-moengage commented on load_balancers/application/variables.tf
> +  type        = list(any)
It should be optional. Else if create_default_alarms is false, still it will ask for alarm_actions

2021-05-31 14:01 UTC, sudip-moengage requested changes
The main filename should be main.tf or alarm.tf not sqs_alarm.tf


Resource name should also be _ separated not - separated.

Sorry that I couldn't mention these in earlier reviews

2021-06-01 09:06 UTC, sudip-moengage approved these changes

2021-06-01 09:06 UTC, merged