Added ec2 core module
moengage/tf-core pull request #7
Opened 2021-03-19 07:03 UTC by ummiyah-moe

2021-03-19 07:07 UTC, akgoel-mo commented on ec2/data.tf
> +    values = ["ubuntu/images/hvm-ssd/ubuntu-focal-20.04-arm64-server-????????"]
Why are we fixing this to arm AMI only? Shouldnt we take the architecture as an input with a default as AMD64?

2021-03-19 07:10 UTC, akgoel-mo commented on ec2/variables.tf
> +    "/dev/sdd",
Shouldnt we support these as nvme*p*? For now, lets support only 5th gen instances and higher, which come with nvme ebs volumes only.

2021-03-19 07:11 UTC, akgoel-mo commented on ec2/outputs.tf
> +  value = aws_instance.ec2.*.id
Lets output both instance id as well as private IP?

2021-03-19 07:12 UTC, akgoel-mo commented on ec2/README.md
> +| ebs\_volume\_type |  | string | n/a | yes |
Missing root_volume_* parameters here. Please reverify variables.tf against README

2021-03-19 07:14 UTC, akgoel-mo commented on ec2/locals.tf
> +    Business    = lower(var.business_name)
Should we add support for custom tags to be passed as a dictionary/map variable and merged with this.

Also Business/Service/SubService/FabTag and overall this tag format, seems moengage specific. For open source, lets keep this generic.

2021-03-19 07:37 UTC, sudip-moengage requested changes

2021-03-19 07:37 UTC, sudip-moengage commented on ec2/README.md
> +
Read me variable should have description, look at other modules for example. You can find description of variables in terraform documentation.

2021-03-19 07:37 UTC, sudip-moengage commented on ec2/data.tf
> +    values = ["ubuntu/images/hvm-ssd/ubuntu-focal-20.04-arm64-server-????????"]
ami should not be hardcode. What if someone want to launch a centos machine? Ideally we should support all latest famous distros like ubuntu, debian, amazon-linux-2, centos. And both the architectures as well.

2021-03-19 07:37 UTC, sudip-moengage commented on ec2/instances.tf
> +  ami                         = coalesce(var.ami_id, data.aws_ami.ubuntu.id)
no ubuntu hardcoding, use locals for all colesce operations.

2021-03-19 07:37 UTC, sudip-moengage commented on ec2/locals.tf
> +    prometheus  = "enabled"
This `prometheus` = enabled should be passed as env variable. It shouldn't belong from core module.

2021-03-19 07:37 UTC, sudip-moengage commented on ec2/locals.tf
> +    Business    = lower(var.business_name)
@akgoel-mo it's already supported.

2021-03-19 07:37 UTC, sudip-moengage commented on ec2/locals.tf
> +    FabTag      = lower(var.fabtag)
@akgoel-mo @ummiyah-moe Let's deprecate fabtag. It's not a standard anymore.

2021-03-19 07:37 UTC, sudip-moengage commented on ec2/variables.tf
> +    "/dev/sdd",
devices names are dynamic. It depends on the type of instance we are launching. The code needs to figure out when to use nvme* and when sd*,

2021-03-19 08:05 UTC, souradeepmoe requested changes

2021-03-19 08:05 UTC, souradeepmoe commented on ec2/data.tf
> +    values = ["ubuntu/images/hvm-ssd/ubuntu-focal-20.04-arm64-server-????????"]
I think we can remove the data variable for aws ami and have the AMI id supplied in every caller module explicitly. One problem that this creates is, whenever there is a new ami available, every caller module would want to destroy and create the instance with the new AMI id. This looks good when we are creating the instance for the first time, but we will almost always have to hardcode the AMI id in the caller module to avoid machine relaunch.

2021-03-24 07:45 UTC, ummiyah-moe commented on ec2/README.md
> +| ebs\_volume\_type |  | string | n/a | yes |
Updated with terraform-docs.

2021-03-24 07:45 UTC, ummiyah-moe commented on ec2/data.tf
> +    values = ["ubuntu/images/hvm-ssd/ubuntu-focal-20.04-arm64-server-????????"]
removed data field and made ami as required input.

2021-03-24 07:46 UTC, ummiyah-moe commented on ec2/locals.tf
> +    FabTag      = lower(var.fabtag)
Its being used in monitoring and confd.

2021-03-24 07:50 UTC, ummiyah-moe commented on ec2/variables.tf
> +    "/dev/sdd",
AWS renames device id with nvm on the machine. - https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/device_naming.html#available-ec2-device-names
Verified launching one machine with sdf volume.

2021-03-24 07:50 UTC, ummiyah-moe commented on ec2/README.md
> +
Updated with terrform-docs

2021-04-05 08:15 UTC, sudip-moengage requested changes

2021-04-05 08:15 UTC, sudip-moengage commented on ec2/locals.tf
> +    FabTag      = lower(var.fabtag)
@ummiyah-moe That's fine. Then the caller module is responsible for passing it along. We should remove it.

2021-04-05 08:15 UTC, sudip-moengage commented on ec2/variables.tf
> +    "/dev/sdf",
What if someone has more than 4 volumes?

2021-04-05 08:24 UTC, ummiyah-moe commented on ec2/variables.tf
> +    "/dev/sdf",
Can you please share the use case of 4 volumes, checked with Amrit/others for kafka they don't need more than 3 volumes. We can add device name for more volumes.

2021-04-08 09:58 UTC, ummiyah-moe commented on ec2/variables.tf
> +    "/dev/sdf",
@sudip-moengage Updated default with other values, please check if this works.

2021-04-08 10:16 UTC, sudip-moengage approved these changes

2021-04-08 10:17 UTC, sudip-moengage commented
@ummiyah-moe I hope this module is tested.

2021-04-16 07:33 UTC, ummiyah-moe commented
terragrunt example - https://github.com/moengage/terragrunt/pull/74

2021-04-16 07:34 UTC, merged