tf-modules for lambda
moengage/tf-core pull request #8
Opened 2021-04-01 06:31 UTC by somashekhar-moe

1. tf-core module for lambda 
2. Lambda function name is kept it to be coming from variable rather than resource-identifies which might not make sense in case of lambda

2021-04-01 06:41 UTC, sudip-moengage requested changes
Where's cloudwatch log group being attached to lambda?

2021-04-01 06:41 UTC, sudip-moengage commented on lambda/lambda.tf
> +resource "aws_cloudwatch_log_group" "example" {
Change name from example to default

2021-04-01 06:41 UTC, sudip-moengage commented on lambda/lambda.tf
> +  retention_in_days = 7
This sjoulfbe variable, which defaults to 7

2021-04-01 06:41 UTC, sudip-moengage commented on lambda/locals.tf
> +  _resource_identifier = "${var.service_name}-${var.subservice_name}"
Add business as prefix as well, look at other modules for reference

2021-04-01 08:58 UTC, somashekhar-moe commented on lambda/lambda.tf
> +resource "aws_cloudwatch_log_group" "example" {
fixed

2021-04-01 08:58 UTC, somashekhar-moe commented on lambda/lambda.tf
> +  retention_in_days = 7
fixed

2021-04-01 08:59 UTC, somashekhar-moe commented
> Where's cloudwatch log group being attached to lambda?

  name              = "/aws/lambda/${var.function_name}"
this is take care like this

2021-04-03 12:54 UTC, sudip-moengage requested changes

2021-04-03 12:54 UTC, sudip-moengage commented on lambda/lambda.tf
> +
So many empty lines, remove this.

2021-04-03 12:54 UTC, sudip-moengage commented on lambda/versions.tf
> +terraform {
I guess we can remove this file.

2021-04-03 20:00 UTC, merged